[package]
name = "shaderforge"
version = "0.1.0"
authors = ["Tom Jakubowski <tom@crystae.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.26.0-alpha3"
